"""add demandstatus

Revision ID: 01afbc515126
Revises: eb2489513ca2
Create Date: 2017-08-09 15:53:00.553284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01afbc515126'
down_revision = 'eb2489513ca2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demands', sa.Column('demandstatus', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demands', 'demandstatus')
    # ### end Alembic commands ###
