"""desigenrinfo

Revision ID: 046ac8a0b243
Revises: 041872451cd1
Create Date: 2017-08-11 09:49:15.694673

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '046ac8a0b243'
down_revision = '041872451cd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('designers', sa.Column('privacy', sa.Integer(), nullable=True))
    op.add_column('designers', sa.Column('startyear', sa.Integer(), nullable=True))
    op.drop_column('designers', 'graduate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('designers', sa.Column('graduate', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('designers', 'startyear')
    op.drop_column('designers', 'privacy')
    # ### end Alembic commands ###
