"""up

Revision ID: 089fe8623ba8
Revises: a4e832680cd7
Create Date: 2017-11-11 17:38:25.799630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '089fe8623ba8'
down_revision = 'a4e832680cd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('unionid', sa.String(length=64), nullable=True),
    sa.Column('sex', sa.Integer(), nullable=True),
    sa.Column('headimg', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unionid')
    )
    op.create_table('posts',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('project_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('up_time', sa.DateTime(), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projectworks',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('work_url', sa.String(length=255), nullable=True),
    sa.Column('post_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('historywork')
    op.drop_table('milestones')
    op.add_column('projects', sa.Column('cat_id', mysql.INTEGER(unsigned=True), nullable=True))
    op.add_column('projects', sa.Column('client_id', mysql.INTEGER(unsigned=True), nullable=True))
    op.add_column('projects', sa.Column('demand_id', mysql.INTEGER(unsigned=True), nullable=True))
    op.add_column('projects', sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=True))
    op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'categories', ['cat_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'demands', ['demand_id'], ['id'])
    op.drop_column('projects', 'milestone_num')
    op.drop_column('projects', 'password')
    op.drop_column('projects', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('description', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('projects', sa.Column('password', mysql.VARCHAR(length=6), nullable=True))
    op.add_column('projects', sa.Column('milestone_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'user_id')
    op.drop_column('projects', 'demand_id')
    op.drop_column('projects', 'client_id')
    op.drop_column('projects', 'cat_id')
    op.create_table('milestones',
    sa.Column('id', mysql.INTEGER(display_width=11, unsigned=True), nullable=False),
    sa.Column('due_time', mysql.DATETIME(), nullable=True),
    sa.Column('de_status', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('cl_status', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('ordinpro', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('due_time_cli', mysql.DATETIME(), nullable=True),
    sa.Column('pro_id', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pro_id'], ['projects.id'], name='milestones_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('historywork',
    sa.Column('id', mysql.INTEGER(display_width=11, unsigned=True), nullable=False),
    sa.Column('work_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('up_time', mysql.DATETIME(), nullable=True),
    sa.Column('milestone_id', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], name='historywork_ibfk_1'),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], name='historywork_ibfk_10'),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], name='historywork_ibfk_11'),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], name='historywork_ibfk_2'),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], name='historywork_ibfk_3'),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], name='historywork_ibfk_4'),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], name='historywork_ibfk_5'),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], name='historywork_ibfk_6'),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], name='historywork_ibfk_7'),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], name='historywork_ibfk_8'),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], name='historywork_ibfk_9'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('projectworks')
    op.drop_table('posts')
    op.drop_table('clients')
    # ### end Alembic commands ###
