"""exp cascade = delete

Revision ID: 13d456c538c0
Revises: 046ac8a0b243
Create Date: 2017-08-12 16:25:19.308606

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '13d456c538c0'
down_revision = '046ac8a0b243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exp_user')
    op.add_column('experiences', sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=True))
    op.create_foreign_key(None, 'experiences', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'experiences', type_='foreignkey')
    op.drop_column('experiences', 'user_id')
    op.create_table('exp_user',
    sa.Column('user_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('exp_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['exp_id'], ['experiences.id'], name='exp_user_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='exp_user_ibfk_2'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
