"""nickname in demandreply

Revision ID: 1b9345217f11
Revises: 7a84489d5ca2
Create Date: 2017-09-13 14:25:37.025808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b9345217f11'
down_revision = '7a84489d5ca2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demands_users', sa.Column('nickname', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demands_users', 'nickname')
    # ### end Alembic commands ###
