"""upgrade

Revision ID: 2e81ed70b178
Revises: 6ddf405f5450
Create Date: 2017-09-14 10:37:59.271164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e81ed70b178'
down_revision = '6ddf405f5450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'demands_recom', 'demands_users', ['deapply_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'demands_recom', type_='foreignkey')
    # ### end Alembic commands ###
