"""up

Revision ID: 39735fb19b26
Revises: 5dda80ca53d9
Create Date: 2017-11-13 15:27:33.013198

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '39735fb19b26'
down_revision = '5dda80ca53d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cashflow', sa.Column('related_client', mysql.INTEGER(unsigned=True), nullable=True))
    op.create_foreign_key(None, 'cashflow', 'clients', ['related_client'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cashflow', type_='foreignkey')
    op.drop_column('cashflow', 'related_client')
    # ### end Alembic commands ###
