"""up

Revision ID: 3d1e9ee9350b
Revises: b5c1d24f7f00
Create Date: 2017-11-02 20:39:14.258665

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d1e9ee9350b'
down_revision = 'b5c1d24f7f00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cashflow',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('change_money', mysql.INTEGER(), nullable=True),
    sa.Column('after_money', mysql.INTEGER(), nullable=True),
    sa.Column('remark', sa.String(length=16), nullable=True),
    sa.Column('when', sa.DateTime(), nullable=True),
    sa.Column('from_who', sa.String(length=4), nullable=True),
    sa.Column('to_who', sa.String(length=4), nullable=True),
    sa.Column('related_user', mysql.INTEGER(unsigned=True), nullable=True),
    sa.ForeignKeyConstraint(['related_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallets',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('alipay', sa.String(length=64), nullable=True),
    sa.Column('tel', sa.String(length=11), nullable=True),
    sa.Column('money', mysql.INTEGER(), nullable=True),
    sa.Column('frozen_money', mysql.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('FKll21eddgtrjc9f40ueeouyr8f', table_name='city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('FKll21eddgtrjc9f40ueeouyr8f', 'city', ['province_id'], unique=False)
    op.drop_table('wallets')
    op.drop_table('cashflow')
    # ### end Alembic commands ###
