"""up

Revision ID: 5dda80ca53d9
Revises: df5f718bad0b
Create Date: 2017-11-13 11:16:11.377820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dda80ca53d9'
down_revision = 'df5f718bad0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('starttime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'starttime')
    # ### end Alembic commands ###
