"""up

Revision ID: 5defaaa3cf22
Revises: 
Create Date: 2017-11-15 20:34:37.285940

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5defaaa3cf22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_user')
    op.drop_table('tb_bargain')
    op.drop_table('tb_demand')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_demand',
    sa.Column('id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('demand_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('start_money', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('end_money', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('aims_money', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('nickname', mysql.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_bargain',
    sa.Column('id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('demand_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('date', mysql.DATETIME(), nullable=False),
    sa.Column('money', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tb_user.id'], name='tb_bargain_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_user',
    sa.Column('id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('uid', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('head_img', mysql.VARCHAR(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
