"""upgrade

Revision ID: 6ddf405f5450
Revises: d67cf822b243
Create Date: 2017-09-13 20:12:37.354885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ddf405f5450'
down_revision = 'd67cf822b243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demands_recom', sa.Column('deapply_id', mysql.INTEGER(unsigned=True), nullable=True))
    op.add_column('demands_recom', sa.Column('nickname', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demands_recom', 'nickname')
    op.drop_column('demands_recom', 'deapply_id')
    # ### end Alembic commands ###
