"""demand fk constrain

Revision ID: 7a84489d5ca2
Revises: f6c049193128
Create Date: 2017-09-13 13:43:40.069636

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7a84489d5ca2'
down_revision = 'f6c049193128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('piwik_log_visit')
    op.drop_table('piwik_archive_numeric_2017_09')
    op.drop_table('piwik_log_conversion_item')
    op.drop_table('piwik_log_link_visit_action')
    op.drop_table('piwik_option')
    op.drop_table('piwik_plugin_setting')
    op.drop_table('piwik_log_conversion')
    op.drop_table('piwik_user')
    op.drop_table('piwik_site_url')
    op.drop_table('piwik_archive_blob_2017_09')
    op.drop_table('piwik_log_profiling')
    op.drop_table('piwik_log_action')
    op.drop_table('piwik_segment')
    op.drop_table('piwik_access')
    op.drop_table('piwik_session')
    op.drop_table('piwik_report')
    op.drop_table('piwik_goal')
    op.drop_table('piwik_sequence')
    op.drop_table('piwik_user_dashboard')
    op.drop_table('piwik_site')
    op.drop_table('piwik_site_setting')
    op.drop_table('piwik_user_language')
    op.drop_table('piwik_logger_message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('piwik_logger_message',
    sa.Column('idlogger_message', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
    sa.Column('tag', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('timestamp', mysql.TIMESTAMP(), nullable=True),
    sa.Column('level', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('message', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('idlogger_message'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('piwik_user_language',
    sa.Column('login', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('language', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('use_12_hour_clock', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('login'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('piwik_site_setting',
    sa.Column('idsite', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('plugin_name', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('setting_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('setting_value', mysql.LONGTEXT(), nullable=False),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('piwik_site',
    sa.Column('idsite', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=90), nullable=False),
    sa.Column('main_url', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('ts_created', mysql.TIMESTAMP(), nullable=True),
    sa.Column('ecommerce', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('sitesearch', mysql.TINYINT(display_width=4), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('sitesearch_keyword_parameters', mysql.TEXT(), nullable=False),
    sa.Column('sitesearch_category_parameters', mysql.TEXT(), nullable=False),
    sa.Column('timezone', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('currency', mysql.CHAR(length=3), nullable=False),
    sa.Column('exclude_unknown_urls', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('excluded_ips', mysql.TEXT(), nullable=False),
    sa.Column('excluded_parameters', mysql.TEXT(), nullable=False),
    sa.Column('excluded_user_agents', mysql.TEXT(), nullable=False),
    sa.Column('group', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('keep_url_fragment', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('idsite'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('piwik_user_dashboard',
    sa.Column('login', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('iddashboard', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('layout', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('login', 'iddashboard'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('piwik_sequence',
    sa.Column('name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('value', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('name'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('piwik_goal',
    sa.Column('idsite', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('idgoal', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('match_attribute', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('pattern', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('pattern_type', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('case_sensitive', mysql.TINYINT(display_width=4), autoincrement=False, nullable=False),
    sa.Column('allow_multiple', mysql.TINYINT(display_width=4), autoincrement=False, nullable=False),
    sa.Column('revenue', mysql.FLOAT(), nullable=False),
    sa.Column('deleted', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('idsite', 'idgoal'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('piwik_report',
    sa.Column('idreport', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('idsite', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('login', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('idsegment', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('period', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('hour', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('type', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('format', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('reports', mysql.TEXT(), nullable=False),
    sa.Column('parameters', mysql.TEXT(), nullable=True),
    sa.Column('ts_created', mysql.TIMESTAMP(), nullable=True),
    sa.Column('ts_last_sent', mysql.TIMESTAMP(), nullable=True),
    sa.Column('deleted', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('idreport'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('piwik_session',
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('modified', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('lifetime', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('data', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('piwik_access',
    sa.Column('login', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('idsite', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('access', mysql.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('login', 'idsite'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('piwik_segment',
    sa.Column('idsegment', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('definition', mysql.TEXT(), nullable=False),
    sa.Column('login', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('enable_all_users', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('enable_only_idsite', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('auto_archive', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('ts_created', mysql.TIMESTAMP(), nullable=True),
    sa.Column('ts_last_edit', mysql.TIMESTAMP(), nullable=True),
    sa.Column('deleted', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('idsegment'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('piwik_log_action',
    sa.Column('idaction', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
    sa.Column('name', mysql.TEXT(), nullable=True),
    sa.Column('hash', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('type', mysql.TINYINT(display_width=3, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('url_prefix', mysql.TINYINT(display_width=2), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('idaction'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('piwik_log_profiling',
    sa.Column('query', mysql.TEXT(), nullable=False),
    sa.Column('count', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('sum_time_ms', mysql.FLOAT(), nullable=True),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('piwik_archive_blob_2017_09',
    sa.Column('idarchive', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('idsite', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('date1', sa.DATE(), nullable=True),
    sa.Column('date2', sa.DATE(), nullable=True),
    sa.Column('period', mysql.TINYINT(display_width=3, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('ts_archived', mysql.DATETIME(), nullable=True),
    sa.Column('value', mysql.MEDIUMBLOB(), nullable=True),
    sa.PrimaryKeyConstraint('idarchive', 'name'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('piwik_site_url',
    sa.Column('idsite', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('url', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('idsite', 'url'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('piwik_user',
    sa.Column('login', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('alias', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('token_auth', mysql.CHAR(length=32), nullable=False),
    sa.Column('superuser_access', mysql.TINYINT(display_width=2, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('date_registered', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('login'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('piwik_log_conversion',
    sa.Column('idvisit', mysql.BIGINT(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('idsite', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('idvisitor', sa.BINARY(length=8), nullable=False),
    sa.Column('server_time', mysql.DATETIME(), nullable=False),
    sa.Column('idaction_url', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('idlink_va', mysql.BIGINT(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('idgoal', mysql.INTEGER(display_width=10), autoincrement=False, nullable=False),
    sa.Column('buster', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('idorder', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('items', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('url', mysql.TEXT(), nullable=False),
    sa.Column('visitor_days_since_first', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('visitor_days_since_order', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('visitor_returning', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('visitor_count_visits', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('referer_keyword', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('referer_name', mysql.VARCHAR(length=70), nullable=True),
    sa.Column('referer_type', mysql.TINYINT(display_width=1, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('config_device_brand', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('config_device_model', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('config_device_type', mysql.TINYINT(display_width=100), autoincrement=False, nullable=True),
    sa.Column('location_city', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('location_country', mysql.CHAR(length=3), nullable=True),
    sa.Column('location_latitude', mysql.DECIMAL(precision=9, scale=6), nullable=True),
    sa.Column('location_longitude', mysql.DECIMAL(precision=9, scale=6), nullable=True),
    sa.Column('location_region', mysql.CHAR(length=2), nullable=True),
    sa.Column('revenue_discount', mysql.FLOAT(), nullable=True),
    sa.Column('revenue', mysql.FLOAT(), nullable=True),
    sa.Column('revenue_shipping', mysql.FLOAT(), nullable=True),
    sa.Column('revenue_subtotal', mysql.FLOAT(), nullable=True),
    sa.Column('revenue_tax', mysql.FLOAT(), nullable=True),
    sa.Column('custom_var_k1', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('custom_var_v1', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('custom_var_k2', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('custom_var_v2', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('custom_var_k3', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('custom_var_v3', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('custom_var_k4', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('custom_var_v4', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('custom_var_k5', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('custom_var_v5', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('idvisit', 'idgoal', 'buster'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('piwik_plugin_setting',
    sa.Column('plugin_name', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('setting_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('setting_value', mysql.LONGTEXT(), nullable=False),
    sa.Column('user_login', mysql.VARCHAR(length=100), server_default=sa.text("''"), nullable=False),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('piwik_option',
    sa.Column('option_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('option_value', mysql.LONGTEXT(), nullable=False),
    sa.Column('autoload', mysql.TINYINT(display_width=4), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('option_name'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('piwik_log_link_visit_action',
    sa.Column('idlink_va', mysql.BIGINT(display_width=10, unsigned=True), nullable=False),
    sa.Column('idsite', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('idvisitor', sa.BINARY(length=8), nullable=False),
    sa.Column('idvisit', mysql.BIGINT(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('idaction_url_ref', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('idaction_name_ref', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('custom_float', mysql.FLOAT(), nullable=True),
    sa.Column('server_time', mysql.DATETIME(), nullable=False),
    sa.Column('idpageview', mysql.CHAR(length=6), nullable=True),
    sa.Column('interaction_position', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('idaction_name', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('idaction_url', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('time_spent_ref_action', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('idaction_event_action', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('idaction_event_category', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('idaction_content_interaction', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('idaction_content_name', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('idaction_content_piece', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('idaction_content_target', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('custom_var_k1', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('custom_var_v1', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('custom_var_k2', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('custom_var_v2', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('custom_var_k3', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('custom_var_v3', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('custom_var_k4', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('custom_var_v4', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('custom_var_k5', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('custom_var_v5', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('idlink_va'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('piwik_log_conversion_item',
    sa.Column('idsite', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('idvisitor', sa.BINARY(length=8), nullable=False),
    sa.Column('server_time', mysql.DATETIME(), nullable=False),
    sa.Column('idvisit', mysql.BIGINT(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('idorder', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('idaction_sku', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('idaction_name', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('idaction_category', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('idaction_category2', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('idaction_category3', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('idaction_category4', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('idaction_category5', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('price', mysql.FLOAT(), nullable=False),
    sa.Column('quantity', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('deleted', mysql.TINYINT(display_width=1, unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('idvisit', 'idorder', 'idaction_sku'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('piwik_archive_numeric_2017_09',
    sa.Column('idarchive', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('idsite', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('date1', sa.DATE(), nullable=True),
    sa.Column('date2', sa.DATE(), nullable=True),
    sa.Column('period', mysql.TINYINT(display_width=3, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('ts_archived', mysql.DATETIME(), nullable=True),
    sa.Column('value', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.PrimaryKeyConstraint('idarchive', 'name'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('piwik_log_visit',
    sa.Column('idvisit', mysql.BIGINT(display_width=10, unsigned=True), nullable=False),
    sa.Column('idsite', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('idvisitor', sa.BINARY(length=8), nullable=False),
    sa.Column('visit_last_action_time', mysql.DATETIME(), nullable=False),
    sa.Column('config_id', sa.BINARY(length=8), nullable=False),
    sa.Column('location_ip', sa.VARBINARY(length=16), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('visit_first_action_time', mysql.DATETIME(), nullable=False),
    sa.Column('visit_goal_buyer', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('visit_goal_converted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('visitor_days_since_first', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('visitor_days_since_order', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('visitor_returning', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('visitor_count_visits', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('visit_entry_idaction_name', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('visit_entry_idaction_url', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('visit_exit_idaction_name', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('visit_exit_idaction_url', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('visit_total_actions', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('visit_total_interactions', mysql.SMALLINT(display_width=5, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('visit_total_searches', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('referer_keyword', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('referer_name', mysql.VARCHAR(length=70), nullable=True),
    sa.Column('referer_type', mysql.TINYINT(display_width=1, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('referer_url', mysql.TEXT(), nullable=True),
    sa.Column('location_browser_lang', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('config_browser_engine', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('config_browser_name', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('config_browser_version', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('config_device_brand', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('config_device_model', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('config_device_type', mysql.TINYINT(display_width=100), autoincrement=False, nullable=True),
    sa.Column('config_os', mysql.CHAR(length=3), nullable=True),
    sa.Column('config_os_version', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('visit_total_events', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('visitor_localtime', mysql.TIME(), nullable=True),
    sa.Column('visitor_days_since_last', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('config_resolution', mysql.VARCHAR(length=18), nullable=True),
    sa.Column('config_cookie', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('config_director', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('config_flash', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('config_gears', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('config_java', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('config_pdf', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('config_quicktime', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('config_realplayer', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('config_silverlight', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('config_windowsmedia', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('visit_total_time', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('location_city', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('location_country', mysql.CHAR(length=3), nullable=True),
    sa.Column('location_latitude', mysql.DECIMAL(precision=9, scale=6), nullable=True),
    sa.Column('location_longitude', mysql.DECIMAL(precision=9, scale=6), nullable=True),
    sa.Column('location_region', mysql.CHAR(length=2), nullable=True),
    sa.Column('custom_var_k1', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('custom_var_v1', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('custom_var_k2', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('custom_var_v2', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('custom_var_k3', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('custom_var_v3', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('custom_var_k4', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('custom_var_v4', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('custom_var_k5', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('custom_var_v5', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('idvisit'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
