"""up

Revision ID: 7db827bec3ba
Revises: 
Create Date: 2017-11-15 21:11:45.706912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7db827bec3ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cashflow', sa.Column('order_no', sa.String(length=9), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cashflow', 'order_no')
    # ### end Alembic commands ###
