"""up

Revision ID: 8e0b86f2a785
Revises: a5ccd3d8d90e
Create Date: 2017-11-02 21:21:38.738811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e0b86f2a785'
down_revision = 'a5ccd3d8d90e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cashflow', sa.Column('status', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cashflow', 'status')
    # ### end Alembic commands ###
