"""up

Revision ID: a4e832680cd7
Revises: 8e0b86f2a785
Create Date: 2017-11-05 20:24:30.421934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4e832680cd7'
down_revision = '8e0b86f2a785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cashflow', sa.Column('detail', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cashflow', 'detail')
    # ### end Alembic commands ###
