"""up

Revision ID: a5ccd3d8d90e
Revises: 3d1e9ee9350b
Create Date: 2017-11-02 21:19:53.651833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5ccd3d8d90e'
down_revision = '3d1e9ee9350b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('name', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'name')
    # ### end Alembic commands ###
