"""up

Revision ID: ae6fe0c85b8e
Revises: 39735fb19b26
Create Date: 2017-11-13 21:16:38.009015

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae6fe0c85b8e'
down_revision = '39735fb19b26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cashflow', sa.Column('project_id', mysql.INTEGER(unsigned=True), nullable=True))
    op.create_foreign_key(None, 'cashflow', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cashflow', type_='foreignkey')
    op.drop_column('cashflow', 'project_id')
    # ### end Alembic commands ###
