"""init

Revision ID: b34ab5a80202
Revises: 
Create Date: 2017-08-09 15:40:00.394763

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b34ab5a80202'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'albums', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'applyforms', 'users', ['user_id'], ['id'])
    op.drop_column('applyforms', 'unionid')
    op.add_column('demands', sa.Column('demandstatus', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'designworks', 'albums', ['album_id'], ['id'])
    op.create_foreign_key(None, 'historywork', 'milestones', ['milestone_id'], ['id'])
    op.alter_column('milestones', 'cl_status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('milestones', 'de_status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('milestones', 'pro_id',
               existing_type=mysql.INTEGER(display_width=11, unsigned=True),
               nullable=True)
    op.create_foreign_key(None, 'milestones', 'projects', ['pro_id'], ['id'])
    op.create_unique_constraint(None, 'users', ['unionid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'milestones', type_='foreignkey')
    op.alter_column('milestones', 'pro_id',
               existing_type=mysql.INTEGER(display_width=11, unsigned=True),
               nullable=False)
    op.alter_column('milestones', 'de_status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('milestones', 'cl_status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_constraint(None, 'historywork', type_='foreignkey')
    op.drop_constraint(None, 'designworks', type_='foreignkey')
    op.drop_column('demands', 'demandstatus')
    op.add_column('applyforms', sa.Column('unionid', mysql.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'applyforms', type_='foreignkey')
    op.drop_constraint(None, 'albums', type_='foreignkey')
    # ### end Alembic commands ###
