"""designerrecom

Revision ID: d12899f390fc
Revises: fda1b6d125b1
Create Date: 2017-08-29 22:17:58.514307

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd12899f390fc'
down_revision = 'fda1b6d125b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demands_recom',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('demand_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('howmuch', sa.String(length=20), nullable=True),
    sa.Column('ideas', sa.String(length=255), nullable=True),
    sa.Column('album_ids', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['demand_id'], ['demands.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demands_recom')
    # ### end Alembic commands ###
