"""upgrade

Revision ID: d67cf822b243
Revises: 1b9345217f11
Create Date: 2017-09-13 19:46:42.005486

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd67cf822b243'
down_revision = '1b9345217f11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demands_recom', sa.Column('howlong', sa.String(length=20), nullable=True))
    op.add_column('demands_recom', sa.Column('worklist', sa.Text(), nullable=True))
    op.drop_column('demands_recom', 'album_ids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demands_recom', sa.Column('album_ids', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('demands_recom', 'worklist')
    op.drop_column('demands_recom', 'howlong')
    # ### end Alembic commands ###
