"""up

Revision ID: df5f718bad0b
Revises: b48c65a5513f
Create Date: 2017-11-11 21:13:18.582112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df5f718bad0b'
down_revision = 'b48c65a5513f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('title', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'title')
    # ### end Alembic commands ###
