"""tmp_deamnd

Revision ID: f6c049193128
Revises: d12899f390fc
Create Date: 2017-09-12 20:16:16.333072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6c049193128'
down_revision = 'd12899f390fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demands_users', sa.Column('tel', sa.String(length=11), nullable=True))
    op.add_column('demands_users', sa.Column('worklist', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demands_users', 'worklist')
    op.drop_column('demands_users', 'tel')
    # ### end Alembic commands ###
