"""add title

Revision ID: fda1b6d125b1
Revises: 814ff026e749
Create Date: 2017-08-25 11:15:40.652515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fda1b6d125b1'
down_revision = '814ff026e749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notices', sa.Column('title', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notices', 'title')
    # ### end Alembic commands ###
