"""up

Revision ID: fdef19ba1380
Revises: b34ab5a80202
Create Date: 2017-08-09 15:49:26.721374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdef19ba1380'
down_revision = 'b34ab5a80202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'demands_users', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'demands_users', type_='foreignkey')
    # ### end Alembic commands ###
