package com.houxiaopang.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class BargainTable implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_bargain.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_bargain.start_money
     *
     * @mbggenerated
     */
    private BigDecimal startMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_bargain.end_money
     *
     * @mbggenerated
     */
    private BigDecimal endMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_bargain.aims_money
     *
     * @mbggenerated
     */
    private BigDecimal aimsMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_bargain.NAME
     *
     * @mbggenerated
     */
    private String name;

    private String nickname;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_bargain.head_img
     *
     * @mbggenerated
     */
    private String headImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_bargain.DATE
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_bargain.money
     *
     * @mbggenerated
     */
    private BigDecimal money;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_bargain.id
     *
     * @return the value of vw_bargain.id
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_bargain.id
     *
     * @param id the value for vw_bargain.id
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_bargain.start_money
     *
     * @return the value of vw_bargain.start_money
     * @mbggenerated
     */
    public BigDecimal getStartMoney() {
        return startMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_bargain.start_money
     *
     * @param startMoney the value for vw_bargain.start_money
     * @mbggenerated
     */
    public void setStartMoney(BigDecimal startMoney) {
        this.startMoney = startMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_bargain.end_money
     *
     * @return the value of vw_bargain.end_money
     * @mbggenerated
     */
    public BigDecimal getEndMoney() {
        return endMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_bargain.end_money
     *
     * @param endMoney the value for vw_bargain.end_money
     * @mbggenerated
     */
    public void setEndMoney(BigDecimal endMoney) {
        this.endMoney = endMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_bargain.aims_money
     *
     * @return the value of vw_bargain.aims_money
     * @mbggenerated
     */
    public BigDecimal getAimsMoney() {
        return aimsMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_bargain.aims_money
     *
     * @param aimsMoney the value for vw_bargain.aims_money
     * @mbggenerated
     */
    public void setAimsMoney(BigDecimal aimsMoney) {
        this.aimsMoney = aimsMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_bargain.NAME
     *
     * @return the value of vw_bargain.NAME
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_bargain.NAME
     *
     * @param name the value for vw_bargain.NAME
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_bargain.head_img
     *
     * @return the value of vw_bargain.head_img
     * @mbggenerated
     */
    public String getHeadImg() {
        return headImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_bargain.head_img
     *
     * @param headImg the value for vw_bargain.head_img
     * @mbggenerated
     */
    public void setHeadImg(String headImg) {
        this.headImg = headImg == null ? null : headImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_bargain.DATE
     *
     * @return the value of vw_bargain.DATE
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_bargain.DATE
     *
     * @param date the value for vw_bargain.DATE
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_bargain.money
     *
     * @return the value of vw_bargain.money
     * @mbggenerated
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_bargain.money
     *
     * @param money the value for vw_bargain.money
     * @mbggenerated
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }
}