package com.houxiaopang.model;

import java.math.BigDecimal;
import java.util.Date;

public class Bargain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bargain.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bargain.demand_id
     *
     * @mbggenerated
     */
    private Long demandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bargain.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bargain.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bargain.money
     *
     * @mbggenerated
     */
    private BigDecimal money;

    public Bargain(Long demandId, Long userId, Date date, BigDecimal money) {
        this.demandId = demandId;
        this.userId = userId;
        this.date = date;
        this.money = money;
    }

    public Bargain(Long id, Long demandId, Long userId, Date date, BigDecimal money) {
        this.id = id;
        this.demandId = demandId;
        this.userId = userId;
        this.date = date;
        this.money = money;
    }

    public Bargain() {

    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bargain.id
     *
     * @return the value of tb_bargain.id
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bargain.id
     *
     * @param id the value for tb_bargain.id
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bargain.demand_id
     *
     * @return the value of tb_bargain.demand_id
     * @mbggenerated
     */
    public Long getDemandId() {
        return demandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bargain.demand_id
     *
     * @param demandId the value for tb_bargain.demand_id
     * @mbggenerated
     */
    public void setDemandId(Long demandId) {
        this.demandId = demandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bargain.user_id
     *
     * @return the value of tb_bargain.user_id
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bargain.user_id
     *
     * @param userId the value for tb_bargain.user_id
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bargain.date
     *
     * @return the value of tb_bargain.date
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bargain.date
     *
     * @param date the value for tb_bargain.date
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bargain.money
     *
     * @return the value of tb_bargain.money
     * @mbggenerated
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bargain.money
     *
     * @param money the value for tb_bargain.money
     * @mbggenerated
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    @Override
    public String toString() {
        return "Bargain{" +
                "id=" + id +
                ", demandId=" + demandId +
                ", userId=" + userId +
                ", date=" + date +
                ", money=" + money +
                '}';
    }
}