package com.houxiaopang.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class Demand implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_demand.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_demand.demand_id
     *
     * @mbggenerated
     */
    private Long demandId;

    private String nickname;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_demand.start_money
     *
     * @mbggenerated
     */
    private BigDecimal startMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_demand.end_money
     *
     * @mbggenerated
     */
    private BigDecimal endMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_demand.aims_money
     *
     * @mbggenerated
     */
    private BigDecimal aimsMoney;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_demand.id
     *
     * @return the value of tb_demand.id
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_demand.id
     *
     * @param id the value for tb_demand.id
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_demand.demand_id
     *
     * @return the value of tb_demand.demand_id
     * @mbggenerated
     */
    public Long getDemandId() {
        return demandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_demand.demand_id
     *
     * @param demandId the value for tb_demand.demand_id
     * @mbggenerated
     */
    public void setDemandId(Long demandId) {
        this.demandId = demandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_demand.start_money
     *
     * @return the value of tb_demand.start_money
     * @mbggenerated
     */
    public BigDecimal getStartMoney() {
        return startMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_demand.start_money
     *
     * @param startMoney the value for tb_demand.start_money
     * @mbggenerated
     */
    public void setStartMoney(BigDecimal startMoney) {
        this.startMoney = startMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_demand.end_money
     *
     * @return the value of tb_demand.end_money
     * @mbggenerated
     */
    public BigDecimal getEndMoney() {
        return endMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_demand.end_money
     *
     * @param endMoney the value for tb_demand.end_money
     * @mbggenerated
     */
    public void setEndMoney(BigDecimal endMoney) {
        this.endMoney = endMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_demand.aims_money
     *
     * @return the value of tb_demand.aims_money
     * @mbggenerated
     */
    public BigDecimal getAimsMoney() {
        return aimsMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_demand.aims_money
     *
     * @param aimsMoney the value for tb_demand.aims_money
     * @mbggenerated
     */
    public void setAimsMoney(BigDecimal aimsMoney) {
        this.aimsMoney = aimsMoney;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    @Override
    public String toString() {
        return "Demand{" +
                "id=" + id +
                ", demandId=" + demandId +
                ", nickname='" + nickname + '\'' +
                ", startMoney=" + startMoney +
                ", endMoney=" + endMoney +
                ", aimsMoney=" + aimsMoney +
                '}';
    }
}