"""category_user

Revision ID: 041872451cd1
Revises: 
Create Date: 2017-08-10 16:07:35.345017

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '041872451cd1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories_users', 'category_name')
    op.drop_column('categories_users', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories_users', sa.Column('id', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False))
    op.add_column('categories_users', sa.Column('category_name', mysql.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
