"""postion

Revision ID: 1a35b65c3740
Revises: 13d456c538c0
Create Date: 2017-08-12 20:22:36.472274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a35b65c3740'
down_revision = '13d456c538c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('designworks', sa.Column('position', sa.Integer(), nullable=True))
    op.add_column('experiences', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiences', 'position')
    op.drop_column('designworks', 'position')
    # ### end Alembic commands ###
