"""uponline

Revision ID: 2c7cfbea4065
Revises: d04fac6e0136
Create Date: 2017-08-15 21:42:46.643857

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c7cfbea4065'
down_revision = 'd04fac6e0136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applyforms', 'unionid')
    op.create_foreign_key(None, 'designworks', 'albums', ['album_id'], ['id'])
    op.create_foreign_key(None, 'historywork', 'milestones', ['milestone_id'], ['id'])
    op.alter_column('milestones', 'cl_status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('milestones', 'de_status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('milestones', 'pro_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_foreign_key(None, 'milestones', 'projects', ['pro_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'milestones', type_='foreignkey')
    op.alter_column('milestones', 'pro_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('milestones', 'de_status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('milestones', 'cl_status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_constraint(None, 'historywork', type_='foreignkey')
    op.drop_constraint(None, 'designworks', type_='foreignkey')
    op.add_column('applyforms', sa.Column('unionid', mysql.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
