"""delte cascade

Revision ID: d04fac6e0136
Revises: 6bceeb1841c5
Create Date: 2017-08-13 17:25:49.966057

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd04fac6e0136'
down_revision = '6bceeb1841c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('designworks_ibfk_1', 'designworks', type_='foreignkey')
    op.drop_column('designworks', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('designworks', sa.Column('user_id', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=True))
    op.create_foreign_key('designworks_ibfk_1', 'designworks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
