"""init

Revision ID: 03153a0f61c3
Revises: f6bfe0e08d9c
Create Date: 2017-09-25 16:52:00.684841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03153a0f61c3'
down_revision = 'f6bfe0e08d9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imgs_tags', sa.Column('screen', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('imgs_tags', 'screen')
    # ### end Alembic commands ###
