"""up

Revision ID: 08970d1d0f9d
Revises: 46391d036ac6
Create Date: 2017-09-28 11:37:01.021739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08970d1d0f9d'
down_revision = '46391d036ac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demands', sa.Column('up_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demands', 'up_time')
    # ### end Alembic commands ###
