"""up

Revision ID: 346349586ff4
Revises: 8a90e6fad62a
Create Date: 2017-10-08 16:38:49.164547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '346349586ff4'
down_revision = '8a90e6fad62a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('tag_name', table_name='tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('tag_name', 'tags', ['tag_name'], unique=True)
    # ### end Alembic commands ###
