"""up

Revision ID: 3a2fc1d5b6f4
Revises: 5d928a343750
Create Date: 2017-09-27 15:49:25.257294

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a2fc1d5b6f4'
down_revision = '5d928a343750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags_screens',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('tag_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('screen', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags_screens')
    # ### end Alembic commands ###
