"""up

Revision ID: 46391d036ac6
Revises: 3a2fc1d5b6f4
Create Date: 2017-09-27 16:00:58.431627

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '46391d036ac6'
down_revision = '3a2fc1d5b6f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screens',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('Screen_name', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tags_screens', sa.Column('screen_id', mysql.INTEGER(unsigned=True), nullable=True))
    op.create_foreign_key(None, 'tags_screens', 'screens', ['screen_id'], ['id'])
    op.drop_column('tags_screens', 'id')
    op.drop_column('tags_screens', 'screen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags_screens', sa.Column('screen', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('tags_screens', sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False))
    op.drop_constraint(None, 'tags_screens', type_='foreignkey')
    op.drop_column('tags_screens', 'screen_id')
    op.drop_table('screens')
    # ### end Alembic commands ###
