"""up

Revision ID: 5d928a343750
Revises: a524669082ea
Create Date: 2017-09-26 11:46:37.714096

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d928a343750'
down_revision = 'a524669082ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demands',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('cat_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('screen', sa.String(length=10), nullable=True),
    sa.Column('imglist', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=8), nullable=True),
    sa.Column('page', sa.String(length=8), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('scale', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['cat_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demands')
    # ### end Alembic commands ###
