"""up

Revision ID: 65c6fda6ab1f
Revises: 511ad186d88e
Create Date: 2017-10-19 14:13:55.009013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65c6fda6ab1f'
down_revision = '511ad186d88e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login_code', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'login_code')
    # ### end Alembic commands ###
