"""up

Revision ID: 740bf4c45868
Revises: 0d3de7151e30
Create Date: 2017-10-17 15:46:05.200080

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '740bf4c45868'
down_revision = '0d3de7151e30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('demand_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('cat_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('uid', sa.String(length=64), nullable=True),
    sa.Column('designer', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['cat_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['demand_id'], ['demands.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_table('posts',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('project_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('up_time', sa.DateTime(), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('designworks',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('work_url', sa.String(length=255), nullable=True),
    sa.Column('post_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('designworks')
    op.drop_table('posts')
    op.drop_table('projects')
    # ### end Alembic commands ###
