"""up

Revision ID: 775046ac8521
Revises: 7f9119637f8e
Create Date: 2017-09-28 20:22:44.378366

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '775046ac8521'
down_revision = '7f9119637f8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demands', sa.Column('tech', sa.String(length=6), nullable=True))
    op.drop_column('demands', 'card_tech')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demands', sa.Column('card_tech', mysql.VARCHAR(length=6), nullable=True))
    op.drop_column('demands', 'tech')
    # ### end Alembic commands ###
