"""up

Revision ID: 7f9119637f8e
Revises: 92c05f715bdd
Create Date: 2017-09-28 20:06:17.405914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f9119637f8e'
down_revision = '92c05f715bdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('cat_id', mysql.INTEGER(unsigned=True), nullable=True))
    op.create_foreign_key(None, 'tags', 'categories', ['cat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_column('tags', 'cat_id')
    # ### end Alembic commands ###
