"""up

Revision ID: 8a90e6fad62a
Revises: 775046ac8521
Create Date: 2017-10-07 14:47:41.708765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a90e6fad62a'
down_revision = '775046ac8521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'imgs_tags', 'screens', ['screen_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'imgs_tags', type_='foreignkey')
    # ### end Alembic commands ###
