"""up

Revision ID: 92c05f715bdd
Revises: 08970d1d0f9d
Create Date: 2017-09-28 14:02:18.016283

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92c05f715bdd'
down_revision = '08970d1d0f9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('uid', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.add_column('demands', sa.Column('business_desc', sa.String(length=32), nullable=True))
    op.add_column('demands', sa.Column('card_tech', sa.String(length=6), nullable=True))
    op.add_column('demands', sa.Column('industry', sa.String(length=8), nullable=True))
    op.add_column('demands', sa.Column('name', sa.String(length=10), nullable=True))
    op.add_column('demands', sa.Column('qrcode', sa.Boolean(), nullable=True))
    op.add_column('demands', sa.Column('tel', sa.String(length=11), nullable=True))
    op.add_column('demands', sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=True))
    op.create_foreign_key(None, 'demands', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'demands', type_='foreignkey')
    op.drop_column('demands', 'user_id')
    op.drop_column('demands', 'tel')
    op.drop_column('demands', 'qrcode')
    op.drop_column('demands', 'name')
    op.drop_column('demands', 'industry')
    op.drop_column('demands', 'card_tech')
    op.drop_column('demands', 'business_desc')
    op.drop_table('users')
    # ### end Alembic commands ###
