"""up

Revision ID: a091efa5a5c8
Revises: e37516617a07
Create Date: 2017-10-09 14:30:12.713899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a091efa5a5c8'
down_revision = 'e37516617a07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('unionid', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'users', ['unionid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'unionid')
    # ### end Alembic commands ###
