"""up

Revision ID: e1e18bd069ef
Revises: 65c6fda6ab1f
Create Date: 2017-10-19 15:55:02.631227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1e18bd069ef'
down_revision = '65c6fda6ab1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('headimg', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'headimg')
    # ### end Alembic commands ###
