"""up

Revision ID: e37516617a07
Revises: 346349586ff4
Create Date: 2017-10-08 21:23:26.870501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e37516617a07'
down_revision = '346349586ff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demands', sa.Column('detailtext', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demands', 'detailtext')
    # ### end Alembic commands ###
