"""init

Revision ID: f6bfe0e08d9c
Revises: 
Create Date: 2017-09-25 16:40:14.830385

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f6bfe0e08d9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('cat_name', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cat_name')
    )
    op.create_table('tags',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('tag_name', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_name')
    )
    op.create_table('imgs_tags',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('tag_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('cat_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.ForeignKeyConstraint(['cat_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imgs_tags')
    op.drop_table('tags')
    op.drop_table('categories')
    # ### end Alembic commands ###
